version: "3.8"

services:
  postgres:
    container_name: "${APP_NAME}-db"
    image: postgres:16
    environment:
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/db/data/${APP_NAME}-postgres:/var/lib/postgresql/data

  server:
    container_name: "${APP_NAME}-server"
    image: dayrim/chatwithrepo-server:latest
    environment:
      PORT: ${PORT}
      APP_ENV: production
      AUTH_SECRET: ${AUTH_SECRET}
      MIXPANEL_PROJECT_TOKEN: ${MIXPANEL_PROJECT_TOKEN}
      POSTGRESQL_CONNECTION: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${APP_NAME}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
